version: "3"

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=mysql

volumes:
  db_data: {}

